INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(9,'Boeing',84591631,'Hank_Russel5@ovock.tech',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(56,'Vodafone',85389032,'Henry_Morris5@bungar.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(35,'Metro Cash&Carry',87732256,'Aiden_Edley5@deavo.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(8,'Comcast',89685161,'Russel_Emerson5@joiniaa.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(30,'Comodo',83208202,'Chad_Curtis5@typill.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(11,'Team Guard SRL',81962639,'Bart_Roman5@grannar.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(28,'Biolife Grup',81863514,'Ryan_Osmond5@zorer.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(4,'Comcast',87333258,'Carl_Aldridge5@jiman.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(56,'Carrefour',80911671,'Leroy_Stewart5@twipet.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(35,'Comodo',87831361,'Julius_Grey5@gompie.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(18,'BuzzFeed',85567712,'Jack_Rosenbloom5@deavo.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(57,'Comodo',85317474,'Wade_Stone5@mafthy.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(49,'Team Guard SRL',89448595,'Barney_Lewis5@iatim.tech',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(2,'Comcast',84912698,'Bart_Pearson5@dionrab.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(9,'Metro Cash&Carry',85278855,'Rick_Marshall5@bungar.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(47,'Erickson',82859686,'Ron_Drake5@extex.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(63,'Team Guard SRL',85744764,'Benjamin_Pond5@nimogy.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(44,'DynCorp',84772771,'Denis_Hepburn5@cispeto.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(12,'It Smart Group',86292492,'Matt_Lynch5@elnee.tech',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(33,'Apple Inc.',82779636,'Jayden_Latham5@zorer.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(3,'AECOM',86153444,'Daron_Dixon5@womeona.net',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(3,'BuzzFeed',81555413,'Caleb_Eastwood5@bungar.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(12,'Areon Impex',80132283,'Johnathan_Norman5@tonsy.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(8,'Comcast',87487391,'Matthew_Cassidy5@bungar.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(44,'BuzzFeed',82092548,'Mike_Woodcock5@twipet.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(58,'CarMax',81757598,'Owen_Wheeler5@famism.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(54,'Apple Inc.',83137523,'Julian_Rodwell5@corti.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(56,'Global Print',88963396,'Percy_Ross5@nickia.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(32,'Comcast',84514726,'Carl_Woodley5@qater.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(12,'ENEL',80209771,'Chris_Walter5@qater.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(42,'Areon Impex',87456798,'Peter_Redfern5@fuliss.net',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(10,'Mars',83796287,'Peter_Cobb5@ubusive.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(48,'Zepter',89328034,'Clint_Rose5@womeona.net',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(57,'Apple Inc.',86007452,'Oliver_Dunbar5@gompie.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(13,'Coca-Cola Company',80975488,'Domenic_Farrow5@nimogy.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(54,'Facebook',84922721,'Daniel_Lynch5@extex.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(14,'Danone',80657216,'Carter_Emmett5@deons.tech',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(33,'AECOM',84978211,'Liam_Camden5@naiker.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(13,'Apple Inc.',85932733,'Doug_Samuel5@jiman.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(31,'Areon Impex',82047331,'Chris_Uttridge5@sveldo.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(17,'21st Century Fox',80598336,'David_Lewis5@guentu.biz',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(4,'Areon Impex',87819262,'Benny_King5@grannar.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(52,'21st Century Fox',83110688,'Cedrick_Lewin5@gmail.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(57,'Coca-Cola Company',89165904,'Chadwick_Stewart5@yahoo.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(33,'Carrefour',80399138,'Benjamin_Latham5@extex.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(54,'Amazon.com',88228793,'Hank_Kelly5@acrit.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(40,'Apple Inc.',86058978,'Harvey_Roscoe5@sheye.org',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(17,'Facebook',81890953,'Wade_Oswald5@atink.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(49,'Team Guard SRL',81683959,'Johnathan_Umney5@cispeto.com',2);
INSERT INTO dbo.Proveedor(idUbicacion, nombreProveedor, celular, correo, estado) VALUES(25,'Facebook',80903968,'Barney_Raven5@elnee.tech',2);

INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(15,6,2.8,255);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(1,6,3.9,175);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(33,2,2.2,164);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(28,5,4.5,141);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(31,7,4.5,280);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(20,13,4.8,261);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(35,6,2.6,217);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(31,1,1.5,254);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(7,8,4.1,108);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(14,9,4.7,152);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(42,10,4.6,260);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(42,8,4.9,174);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(6,8,3.1,234);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(13,11,3.3,240);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(26,3,2.7,116);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(6,8,3.4,226);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(39,13,1.5,293);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(2,8,2.8,248);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(5,4,1.1,231);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(30,12,4.5,259);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(25,14,2.6,250);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(33,5,1.8,237);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(16,13,2.1,218);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(10,6,1.1,226);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(35,8,4.8,223);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(12,14,1.1,196);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(16,11,1.7,127);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(39,8,1.9,160);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(34,6,2.1,187);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(11,14,4.4,191);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(10,10,3.8,116);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(49,4,2.4,202);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(36,3,1.5,175);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(28,11,3.1,262);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(32,5,2.8,289);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(16,4,3.4,179);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(14,1,3.6,157);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(33,2,2.5,130);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(27,2,3.2,214);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(26,6,4.8,273);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(25,5,4.3,261);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(42,4,4.3,255);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(37,10,1.5,148);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(36,8,2.1,242);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(24,7,1,154);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(28,11,1.8,186);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(46,7,4.8,278);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(46,4,4.3,186);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(20,5,2.1,181);
INSERT INTO dbo.ProveedorxProducto(idProveedor, idProducto, costoProducto, cantidadDisponible) VALUES(44,1,3.4,269);
